
# SEO
title: Swiss Jekyll Theme
description: A bold typographic theme inspired by Swiss design.

# social
social_link: facebook
social_username: avtishin
github_repo: inveterate # the GitHub repo name for your project
github_username: avtishin
theme_color: red

# Theme
remote_theme: 'internet-de-france/swiss'
baseurl: '/inveterate'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


